# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://archives.albany.edu" # the base hostname & protocol for your site, e.g. http://example.com
# I have to swap this with the above when dns switches
url: "https://archives.albany.edu"
rooturl: "https://archives.albany.edu"
#url: "http://lib-espy-ws-d101.its.albany.edu" # the base hostname & protocol for your site, e.g. http://example.com
#rooturl: "http://lib-espy-ws-d101.its.albany.edu"
twitter_username: jekyllrb
github_username:  jekyll

# pagination settings
paginate: 10
paginate_path: "/blog/page:num/"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-last-modified-at
  #- jekyll/tagging
  # There are no links to tags for posts so I removed this for now

# for creating new empty arrays
emptyArray: []

#tag_page_layout: tag_page
#tag_page_dir: tag

collections:
  selections:
    output: true
  updates:
    output: true
  slider:
    output: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
