services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: website
    ports:
      - '4000:4000'
    environment:
      - TZ=America/New_York
      - JEKYLL_ENV=production
      - JEKYLL_CACHE_DIR=/tmp/.jekyll-cache
    volumes:
      - jekyll-site:/code
      - .:/tmp-src:ro
    working_dir: /code
    command: >
      bash -c "
        rm -rf /code/_site &&
        echo 'Copying files...' &&
        rsync -a /tmp-src/ /code/ &&
        echo 'Serving site...' &&
        jekyll serve --incremental --config _config.yml,_config_dev.yml"

  sync:
    image: alpine:latest
    container_name: jekyll_sync
    volumes:
      - .:/src:ro
      - jekyll-site:/dst
    command: >
      sh -c "
        apk add --no-cache rsync &&
        while true; do
          rsync -a --update /src/ /dst/;
          sleep 1;
        done"

volumes:
  jekyll-site: {}
