services:
  server:
    image: jekyll/jekyll:4
    container_name: website
    ports:
      - '4000:4000'
    environment:
      - TZ=America/New_York
      - JEKYLL_ENV=development
    volumes:
      - jekyll-site:/code
      - .:/tmp-src:ro
    working_dir: /code
    command: >
      bash -c 'apk add --no-cache rsync &&
               rm -rf /code/.jekyll-cache /code/_site &&
               echo "Copying files..." &&
               rsync -a /tmp-src/ /code/ &&
               echo "Installing dependencies..." &&
               bundle install &&
               chown -R jekyll:jekyll /code &&
               echo "Serving site..." &&
               jekyll serve --incremental --config _config.yml,_config_dev.yml'
  sync:
    image: alpine:latest
    container_name: jekyll_sync
    volumes:
      - .:/src:ro
      - jekyll-site:/dst
    command: >
      sh -c "apk add --no-cache rsync &&
             while true; do
               rsync -a --update /src/ /dst/;
               sleep 1;
             done"

volumes:
  jekyll-site: {}
